In [1]:
# Mencetak nama dan NPM
print('Nama: Aditya Rimandi Putra')  # Mencetak nama
print('NPM : 41155050210030\n')  # Mencetak NPM

#table logika AND 2 input
"""
X1 X2 y
1  1  1
1  0  0
0  0  0
0  0  0
"""

Nama: Aditya Rimandi Putra
NPM : 41155050210030



'\nX1 X2 y\n1  1  1\n1  0  0\n0  0  0\n0  0  0\n'

In [2]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Penggunaan Machine Learning dengan TensorFlow/Keras
import tensorflow as tf  # Mengimpor library TensorFlow
from tensorflow import keras  # Mengimpor modul Keras dari TensorFlow
import numpy as np  # Mengimpor library NumPy untuk pengolahan numerik

# Definisikan model Machine Learning
model = keras.Sequential([
    keras.Input(shape=(2,)),  # Lapisan Input dengan 2 dimensi input
    keras.layers.Dense(units=1)  # Lapisan Dense dengan 1 neuron output
])

# Kompilasi model dengan optimizer dan fungsi loss
model.compile(optimizer='sgd', loss='mean_squared_error')
#   - optimizer='sgd' menggunakan algoritma optimasi Stochastic Gradient Descent (SGD)
#   - loss='mean_squared_error' menggunakan fungsi loss Mean Squared Error (MSE)


Nama: Aditya Rimandi Putra
NPM : 41155050210030



In [3]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Definisikan data input dan target
xs = np.array([
    [1,1], [1,0], [0,1], [0,0]
], dtype=int)  # Data input (X1 dan X2)
ys = np.array(
    [1, 0, 0, 0], dtype=int
)  # Data target (y)

Nama: Aditya Rimandi Putra
NPM : 41155050210030



In [4]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Tampilkan arsitektur model awal
model.summary()
#   - model.summary() digunakan untuk menampilkan informasi tentang arsitektur model
#   - Informasi yang ditampilkan meliputi jumlah lapisan, jenis lapisan, jumlah parameter, dan lain-lain

Nama: Aditya Rimandi Putra
NPM : 41155050210030



Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Cek bobot model awal
weights = model.get_weights()  # Mendapatkan bobot model awal
weights  # Menampilkan bobot model awal
#   - model.get_weights() digunakan untuk mendapatkan bobot model awal
#   - Bobot model awal adalah nilai awal yang digunakan oleh model sebelum dilakukan pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030



[array([[-0.3865254],
        [-1.3775923]], dtype=float32),
 array([0.], dtype=float32)]

In [6]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Pelatihan model
model.fit(xs, ys, epochs=1000)  # Melakukan pelatihan model dengan data xs dan ys selama 1000 epoch
#   - model.fit() digunakan untuk melakukan pelatihan model
#   - xs adalah data input yang digunakan untuk pelatihan
#   - ys adalah data target yang digunakan untuk pelatihan
#   - epochs=1000 menentukan jumlah epoch yang digunakan untuk pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step - loss: 2.4219
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.3048
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.1948
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.0914
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.9944
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.9032
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.8175
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.7370
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.6614
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.5902
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.5234
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.4605
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1.4014
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1.3457
Epoch 15/1000
1/1 ━━━

In [7]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Uji model
data = np.array([[1, 1]])  # Data input yang digunakan untuk uji
answer = model.predict(data)  # Melakukan prediksi dengan model
print(answer)  # Menampilkan hasil prediksi
#   - model.predict() digunakan untuk melakukan prediksi dengan model
#   - data adalah data input yang digunakan untuk uji
#   - hasil prediksi adalah output yang dihasilkan oleh model berdasarkan data input

Nama: Aditya Rimandi Putra
NPM : 41155050210030

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[0.71846557]]


In [8]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Cek bobot model setelah pelatihan
weights = model.get_weights()  # Mendapatkan bobot model setelah pelatihan
weights  # Menampilkan bobot model setelah pelatihan
#   - model.get_weights() digunakan untuk mendapatkan bobot model setelah pelatihan
#   - Bobot model setelah pelatihan adalah nilai bobot yang telah diupdate setelah proses pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030



[array([[0.46455055],
        [0.45795608]], dtype=float32),
 array([-0.20404105], dtype=float32)]

In [9]:
# Mencetak nama dan NPM
print('Nama: Aditya Rimandi Putra')  # Mencetak nama
print('NPM : 41155050210030\n')  # Mencetak NPM

#table data
"""
w1 = 2
w2 = 4

x1 x2 y
2  3  16
4  1  12
5  4  28
7  5  34
8  2  24
2  1  8
4  9  44
8  2  24
7  1  18
6  5  32
1  1  6
3  2  14
"""

Nama: Aditya Rimandi Putra
NPM : 41155050210030



'\nw1 = 2\nw2 = 4\n\nx1 x2 y\n2  3  16\n4  1  12\n5  4  28\n7  5  34\n8  2  24\n2  1  8\n4  9  44\n8  2  24\n7  1  18\n6  5  32\n1  1  6\n3  2  14\n'

In [11]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Definisikan model baru
model2 = keras.Sequential([
    keras.Input(shape=(2,)),  # Lapisan Input dengan 2 dimensi input
    keras.layers.Dense(units=1)  # Lapisan Dense dengan 1 neuron output
])  # Model baru dengan 1 lapisan Dense dan 1 neuron output
#   - units=1 menentukan jumlah neuron output
#   - input_shape=[2] menentukan jumlah input

# Kompilasi model baru
model2.compile(optimizer='sgd', loss='mean_squared_error')
#   - optimizer='sgd' menentukan algoritma optimasi yang digunakan
#   - loss='mean_squared_error' menentukan fungsi loss yang digunakan

# Definisikan data input dan target
xs = np.array(
    [
        [2, 3], [4, 1], [5, 4], [7, 5], [8, 2], [2,1],
        [4, 9], [8, 2], [7, 1], [6, 5], [1, 1], [3, 2]
    ]
)  # Data input
ys = np.array(
    [16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14]
)  # Data target
#   - xs dan ys adalah data yang digunakan untuk pelatihan model

Nama: Aditya Rimandi Putra
NPM : 41155050210030



In [12]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Cek bobot model awal
weights = model2.get_weights()  # Mendapatkan bobot model awal
weights  # Menampilkan bobot model awal
#   - model2.get_weights() digunakan untuk mendapatkan bobot model awal
#   - Bobot model awal adalah nilai bobot yang digunakan oleh model sebelum dilakukan pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030



[array([[-0.03973806],
        [-0.7406058 ]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Pelatihan model
model2.fit(xs, ys, epochs=1000)  # Melakukan pelatihan model dengan data xs dan ys selama 1000 epoch
#   - model2.fit() digunakan untuk melakukan pelatihan model
#   - xs adalah data input yang digunakan untuk pelatihan
#   - ys adalah data target yang digunakan untuk pelatihan
#   - epochs=1000 menentukan jumlah epoch yang digunakan untuk pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 737.4894
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 70.7323
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 29.6204
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 22.7840
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 18.6162
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 15.2833
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 12.5616
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 10.3359
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 8.5157
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 7.0271
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 5.8097
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 4.8140
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3.9997
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 3.3337
Epoch 15/100

In [15]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Uji model
data = np.array([[1, 3]])  # Data input yang digunakan untuk uji
answer = model2.predict(data)  # Melakukan prediksi dengan model
print(answer)  # Menampilkan hasil prediksi
#   - model2.predict() digunakan untuk melakukan prediksi dengan model
#   - data adalah data input yang digunakan untuk uji
#   - hasil prediksi adalah output yang dihasilkan oleh model berdasarkan data input

# Seharusnya hasil prediksi adalah 14
#   - 1*2 + 3*4 = 14 adalah perhitungan yang seharusnya dilakukan oleh model

Nama: Aditya Rimandi Putra
NPM : 41155050210030

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[14.167524]]


In [16]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Cek bobot model setelah pelatihan
weights = model2.get_weights()  # Mendapatkan bobot model setelah pelatihan
weights  # Menampilkan bobot model setelah pelatihan
#   - model2.get_weights() digunakan untuk mendapatkan bobot model setelah pelatihan
#   - Bobot model setelah pelatihan adalah nilai bobot yang telah diupdate setelah proses pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030



[array([[2.0007617],
        [4.0290146]], dtype=float32),
 array([0.07971901], dtype=float32)]

In [ ]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Uji model
data = np.array([[3, 3]])  # Data input yang digunakan untuk uji
answer = model2.predict(data)  # Melakukan prediksi dengan model
print(answer)  # Menampilkan hasil prediksi
#   - model2.predict() digunakan untuk melakukan prediksi dengan model
#   - data adalah data input yang digunakan untuk uji
#   - hasil prediksi adalah output yang dihasilkan oleh model berdasarkan data input

# Seharusnya hasil prediksi adalah 18
#   - 3*2 + 3*4 = 18 adalah perhitungan yang seharusnya dilakukan oleh model

Nama: Aditya Rimandi Putra
NPM : 41155050210030

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[18.169048]]


In [20]:
# Mencetak informasi identitas
print('Nama: Aditya Rimandi Putra')  # Mencetak nama lengkap
print('NPM : 41155050210030\n')  # Mencetak Nomor Pokok Mahasiswa (NPM)

# Cek bobot model setelah pelatihan
weights = model2.get_weights()  # Mendapatkan bobot model setelah pelatihan
weights  # Menampilkan bobot model setelah pelatihan
#   - model2.get_weights() digunakan untuk mendapatkan bobot model setelah pelatihan
#   - Bobot model setelah pelatihan adalah nilai bobot yang telah diupdate setelah proses pelatihan

Nama: Aditya Rimandi Putra
NPM : 41155050210030



[array([[2.0007617],
        [4.0290146]], dtype=float32),
 array([0.07971901], dtype=float32)]